config/routes.rb
Rails.application.routes.draw do
  resources :searches
  root 'albums#homepage'

  resources :albums
  
  resources :albums do
    member do
    delete :delete_upload
    end
  end
  get "allimages" => 'albums#allimages'
  devise_for :users, controllers: { registrations: "registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
    paginates_per 3
    belongs_to :user
    has_many_attached :images
  

    validates :title, presence: true
    validates :discription, presence: true
    #validates :image_type 

    def thumbnail input
        return self.images[input].variant(resize: '300x300!').processed
    end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord

    def thumbnail input
        return self.images[input].variant(resize: '300x400!').processed
    end

end

app/models/search.rb
class Search < ApplicationRecord

    def search_albums

        albums = Album.all
      
        albums = users.where(["user LIKE ?" "%#{user}%"]) if user.present?
        albums = albums.where(["title LIKE ?" "%#{title}%"]) if title.present?
        albums = albums.where(["discription LIKE ?" "%#{description}%"]) if description.present?
        albums = albums.where(["tag LIKE ?" "%#{tag}%"]) if tag.present?

        return albums
    end


end

app/models/user.rb
class User < ApplicationRecord
  has_many :albums
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index, :allimages, :destroy_album, :homepage ]
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def allimages
   
    @albums = Album.where(["title LIKE ?", "%#{params[:search]}%"]).page(params[:page])

 end
  def index


  
    var = current_user.admin
    if var ==true
      @search = Album.ransack(params[:q])
      @albums = @search.result.includes(:user).page(params[:page])
     

    else
     
      @search= current_user.albums.ransack(params[:q])
      @albums = @search.result.includes(:user).page(params[:page])
      

    end
   

  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  
  end
  
  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)
    @album.user = current_user
    respond_to do |format|
      if @album.save

        format.html { redirect_to @album, notice: 'Album was successfully created.' }

        AlbumMailer.create_album(@album).deliver_now
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        AlbumMailer.edit_album(@album).deliver_now
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end
  def homepage
    if user_signed_in?
      redirect_to albums_path
    end

    @albums = Album.all

  end
  # DELETE /albums/1
 
  # DELETE /albums/1.json
  def destroy
    
   @album.destroy
       respond_to do |format|
       
        format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
        AlbumMailer.destroy_album(@album).deliver_now
        format.json { head :no_content }
       end
  end

  def delete_upload
    attachment = ActiveStorage::Attachment.find(params[:id])
    attachment.purge # or use purge_later
    redirect_back(fallback_location: albums_url)
  end

 

 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:title, :discription,  :tag, :publish, images: [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to albums_path
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit(:name, :email,:admin, :password, :password_confirmation )
    end

    def account_update_params
        params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation, :current_password)
    end
    
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  #before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /searches
  # GET /searches.json
  def index
    
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
  #  @search = Search.new(search_params[:id])
  end

  # GET /searches/new
  def new
    @search = Search.new
    @titles = Album.all.pluck(:title)
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)
    redirect_to @search
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json

  # DELETE /searches/1
  # DELETE /searches/1.json

  def search_albums

    albums = Album.all
  end


end
 
  private
    # Use callbacks to share common setup or constraints between actions.

    # Only allow a list of trusted parameters through.
    def search_params
      params.require(:search).permit(:user, :title, :description, :tag)
    end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
<% if album.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

    <ul>
        <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="row ">

    <div class="container ">
        <div class="row h5">
            <div class="col-4 ">

            </div>
            <div class="col-6 shadow-lg pt-4 bg-dark">

                <div class="row pb-2">
                    <div class="col-3">
                        <%= form.label :title %>
                    </div>
                    <div class="col-9">

                        <%= form.text_field :title %>
                    </div>
                </div>

                <div class="row pb-2">
                    <div class="col-3">

                        <%= form.label :description %>
                    </div>
                    <div class="col-9">

                        <%= form.text_field :discription %>
                    </div>
                </div>

                <div class="row pb-2">
                    <div class="col-3">
                        <%= form.label :tag %>
                    </div>
                    <div class="col-9">
                        <%= form.text_field :tag %>
                    </div>
                </div>
                   
                 <div class="row pb-2">
                <div class="col-3">

                </div>
                <div class="col-9">
                <%= form.check_box :publish %>
                    <%= form.label :publish,"Publish " %>
                    
                </div>
            </div>



                <div class="row pb-2">
                    <div class="col-3">

                        <%= form.label :images %>
                    </div>
                    <div class="col-9">

                        <%= form.file_field :images, multiple: true %>
                    </div>
                </div>

                <div class="row pb-2">
                    <div class="col-7">
                    <div class="actions">
                            <%= form.submit %>
                        </div>
                    </div>
                    <div class="col-5">
                    <button class="float-left">
                    <%= link_to 'Back', albums_path %>
                </button>
                    </div>

                </div>
               
                </div>

            </div>
            <div class="col-3">

            </div>
        </div>


    </div>
</div>

<% end %>

app/views/albums/allimages.html.erb
<div class="jumbotron">
<div class="container  ">
<h1 class="text-center text-success">Recent Uploaded </h1>
    <div class="row border-dark mb-5 pt-5">
        <% @albums.each do |album| %>
        <div class="col mr-2 card">

            <div class="card-body ">
                <p><strong>User: </strong><%= album.user.email.split('@')[0] %></p>
                <p><strong>Title: </strong><%= album.title %></p>
                <p><strong>Published On: </strong><span class="text-muted"><%= album.created_at.to_s.split(' ')[0] %></span></p>
                <p><strong>Last Updated: </strong><span class="text-muted"><%= album.updated_at.to_s.split(' ')[0] %></span></p>
                <%= link_to 'Show', album , class:'btn btn-primary text-white btn-sm' %>
            </div>
        </div>
        <% end %>
    </div>
</div>
<%= paginate @albums %>
</div>

app/views/albums/edit.html.erb
<body class="bg-success">
<div class="container ">
    <div class="row">
        <div class="col text-center mt-4">
        <h1>Editing Album </h1>
        </div>
        </div>
    </div>
    
    <div  class="text-white">

<%= render 'form', album: @album %>


</div>

</body>

app/views/albums/homepage.html.erb
     
     <div class="carousel-inner  ">
            <div class="carousel-item active">
                <div class="image-fluid ">
                    <%= image_tag  "https://posterjackcanada.files.wordpress.com/2013/12/silhouette-photographer-tripod-sunset-sunrise.jpg", width: "1300px ", height: "550px"%>
                </div>
                <div class="carousel-caption " , style=padding-left:540px>
                    
                    <h4>"The nice things about the gallery shows is that without having to pay any money you can just go and see it."</h4>
                </div>
            </div>
        </div>  

<div class="container-fluid mb-2 pt-1  jumbotron">
    <div class="row-fluid  text-danger pb-2">
        <h1 id="publish" class="font-weight-bolder jumbotron">Recent Album published by user:</h1>
    </div>
    <div class="container">
        <div class="row mb-5 pt-1 justify-content-md-center">
            <% @albums.each do |album| %>
            <% if album.publish? %>
            <div class="col-3 m-4 card">

                <div class="card-body ">
                    
                    <p><strong>Title: </strong><%= album.title %></p>
                    <p><strong>Published On: </strong><span class="text-muted"><%= album.created_at.to_s.split(' ')[0] %></span></p>
                    <p><strong>Last Updated: </strong><span class="text-muted"><%= album.updated_at.to_s.split(' ')[0] %></span></p>
                    <p><strong>  Tags : </strong><span class="text-muted"><%= album.tag %></span></p>
                    <%= link_to 'Show', album , class:'btn btn-primary text-white btn-sm' %>
                </div>
                <div class="card-footer text-muted">
                    
                    <p><strong>User: </strong><%= album.user.email.split('@')[0] %></p>
                </div>
            </div>
            <% end %>
            <% end %>
        </div>


    </div>
</div>

app/views/albums/index.html.erb
<div class="jumbotron">
<p id="notice"><%= notice %></p>
<div class="container">
  <h1 class="display-2 text-center text-success">Gallery<h1>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-4">
      <%= search_form_for @search do |f| %>
      <%= f.text_field :title_or_discription_cont, class: " rounded "%>
      <%= f.submit "Search", class: "rounded btn-secondary" %>
      <% end %>
    </div>
    <div class="col-8 text-right  h2 "><u>
    <%= link_to 'Create New Gallery', new_album_path %></u>
    </div>
  </div>   
</div>     
  

  <table class="table table-warning table-hover table-bordered text-center ">
    <thead class="h4">
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Created On </th>
        <th>Updated On </th>
        <th>Show Album</th> 
        <th>Edit Album</th>
        <th>Destroy Album</th>
        <!--  <th colspan="3"></th> -->
      </tr>
    </thead>

   <tbody>
     <% @albums.each do |album| %>
     <tr>
        <td class="h6"><%= album.title %></td>
        <td class="h6"><%= album.discription %></td>
        <td class="h6"><%= album.created_at.to_s.split(' ')[0] %></td>
        <td class="h6"> <%= album.updated_at.to_s.split(' ')[0] %></td>
        <td class="h6"><%= link_to 'Show', album %></td>
        <td class="h6"><%= link_to 'Edit', edit_album_path(album) %></td>
        <td class="h6"><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>


     </tr>
     <% end %>
    </tbody>
    </table>
<br>
<%= paginate @albums%>

</div>

app/views/albums/new.html.erb
<body class="bg-success">
<div class="container ">
    <div class="row">
        <div class="col text-center mt-4">
            <h1>New Album</h1>
        </div>
    </div>
</div>

<div  class="text-white">
    <%= render 'form', album: @album %>
</div>

</body>

app/views/albums/show.html.erb
<% if user_signed_in? %>
<p id="notice"><%= notice %></p>
<div class="container text-center  p-3 mb-4 shadow bg-white rounded">
<h1 class="text-success display-2">Gallery</h1>
</div>



<div class="container jumbotron-fluid pt-4">
    <div class="row">
        <% (0...@album.images.count).each do |image| %>
        <div class="col-4 pt-3">
            <div class="card-group ">
                <div class="card">
                    <%= image_tag(@album.thumbnail(image) )%>

                    <div class="card-body">
                        <h5 class="card-title">
                            Title:
                            <%= @album.title %></h5>
                        <h5>
                            Description:
                            <%= @album.discription %></h5>
                        <p class="">Publish On :<%= @album.created_at.to_s.split(' ')[0] %></p>
                        <p> Tags: <%= @album.tag %> </p>
                        
                        <% if current_user.admin? || current_user.email == @album.user.email %>
                        <div>


                            <%= link_to 'Remove', delete_upload_album_url(@album.images[image]), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning float-left shadow-lg" %>
                        </div>
                        <% end %>
                    </div>


                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>
<div class="container ">

    <div class="row">

        <div class="col-5 ">
            
        </div>
        <% if current_user.admin? || current_user.email == @album.user.email %>

        <div class="col-1 ">
            <%= link_to 'Edit', edit_album_path(@album), class: "btn btn-lg btn-info float- text-white" %>

        </div>
        <% end %>
        <div class="col-1 ">
            <%= link_to 'Back', albums_path, class:"btn btn-lg btn-info  text-center float-right text-white" %>


        </div>
        <div class="col-5"></div>
    </div>
</div>

<% else %>









<div class="container pt-4">
    <div class="row">
        <% (0...@album.images.count).each do |image| %>
        <div class="col-4 pt-3">
            <div class="card-group ">
                <div class="card">
                    <%= image_tag(@album.thumbnail(image) )%>
                </div>

            </div>
            
        </div>
        <% end %>
    </div>
</div>

<% end %>

app/views/home/index.html.erb
<nav class="navbar navbar-expand-md bg-dark navbar-dark sticky-top">
      <div class="container">
      <%= image_tag "https://image.flaticon.com/icons/png/512/69/69524.png", width:"30px", height:"30px"%>&nbsp &nbsp
         <a href="#" class="navbar-brand text-warning font-weight-bold">ALBUM</a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsenavbar">
          <span class="navbar-toggler-icon"</span></button>
          <div class="collapse navbar-collapse text-center" id="collapsenavbar">
            
           
            <ul class="navbar-nav ml-auto text-white ">
            <li class="nav-item btn-danger">
            <%= link_to  "Recent Upload", allimages_path, class:"nav-link" %>
          </li>&nbsp &nbsp
          
                <li class="nav-item  btn-primary  "> <a class="nav-link" href="/users/sign_in">Log In</a></li>&nbsp &nbsp
                 <li class="nav-item  btn-primary  "> <a class="nav-link" href="/users/sign_up">Sign up</a></li>&nbsp

            </ul>
         </div>
     </nav>  
     
     <div class="carousel-inner  ">
            <div class="carousel-item active">
                <div class="image-fluid ">
                    <%= image_tag  "https://posterjackcanada.files.wordpress.com/2013/12/silhouette-photographer-tripod-sunset-sunrise.jpg", width: "1300px ", height: "550px"%>
                </div>
                <div class="carousel-caption " , style=padding-left:540px>
                    
                    <h4>"The nice things about the gallery shows is that without having to pay any money you can just go and see it."</h4>
                </div>
            </div>
        </div>  
<div class="container mb-4 pt-5">
    <div class="row-fluid pb-2">
        <h1 id="portfolio" class="font-weight-bolder text-danger text-center">COLLECTIONS  </h1>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-6 col-sm-6">
            <div class="">
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQYh-gwkaik2hwrBRWcjqm-LHucQGKcqVGdE6B5pMuAjzz_zLGb&usqp=CAU" width="350px " height="350px" %>

            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-6">
            <div class="">
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTAXZVFuGtOp81jEcia49-YibHU8mgVzivLVftGz4tH7eHUCJLn&usqp=CAU" width="350px " height="350px" %>
               

            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-6">
            <div class="">
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQdyEXW2HmUZCYRANauFZU-fNyUcSAxOmUIf7FDrxwnieJuwNaI&usqp=CAU" width="350px " height="350px" %>
                
            </div>
        </div>
    </div>
    <div class="row pt-5">
        <div class="col-lg-4 col-md-6 col-sm-6">
            <div class="">
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQcacsK2HXSdY700Y_ci0cyojUc8z_aXc9BvtXT5gT5gL30noj1&usqp=CAU" width="350px" height="350px">
              

            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-6">
            <div class="">
                <img src="https://freeaddon.com/wallpaper/cats/thumb444x250-04.jpg" width="350px " height="350px" %>
                

            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-6">
            <div class="">
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTaY-3WcQ8ploNJ3-MpeWdkdIQ9wto4Cccz-4zpRn24owEN8soK&usqp=CAU" width="350px " height="350px" %>
             

            </div>
        </div>
    </div>

</div>

<div class="container">
    <hr>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Gallery</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
        <a class="navbar-brand text-warning" href="#"><strong>ALBUM</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <%= link_to  "Home", root_path, class:"nav-link text-white" %>
                </li>
                <% if user_signed_in? %>

                <li class="nav-item">
                    <%= link_to  "Recent Upload", allimages_path, class:"nav-link" %>
                </li>

                <% end %>

            </ul>
            <ul class="navbar-nav ml-auto ">
                <% unless user_signed_in? %>
                <li class="">
                    <a class="nav-link btn btn-primary" href="/users/sign_in">Log In</a>
                </li> &nbsp &nbsp
                <li class="">
                    <a class="nav-link btn btn-danger" href="/users/sign_up">Sign up</a>
                </li>
                <% end %>
                <% if user_signed_in? %>
                <li class="btn btn-danger btn-sm">
                    <%= link_to "SignOut", destroy_user_session_path, :method => 'delete', class: "nav-link" %>
                </li>
                <% end %>
            </ul>
        </div>
    </nav>

    
    <%= yield %>
</body>

</html>

app/views/searches/index.html.erb
<p id="notice"><%= notice %></p>

<% if @search.search_albums? %>
<p> No Record Found </p>

<% else %>

<% @search.search_albums.each do |sea| %>
<p>
    <strong>User:</strong>
    <%= @sea.user %>
</p>

<p>
    <strong>Title:</strong>
    <%= @sea.title %>
</p>

<p>
    <strong>Description:</strong>
    <%= @sea.description %>
</p>

<p>
    <strong>Tag:</strong>
    <%= @sea.tag %>
</p>
<% end %>
<% end %>

<%= link_to 'Back', new_searches_path %>

app/views/searches/new.html.erb
<h1>New Search</h1>


<%= form_for @search  do |f| %>
   <div class="form-inputs">
    <%= f.text_field :user %>
    <%= f.select :title, options_for_select(@titles), :include_blank => true %>
    <%= f.text_field :description %>
    <%= f.text_field :tag %>
  </div>

  <div class="form-actions">
    <%= f.submit :submit %>
  </div>
<% end %>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>
<div>
    <% if @search.search_albums.empty?%>
    <p> No Record Found </p>

    <% else %>

    <% @search.search_albums.each do |sea| %>
    <p>
        <strong>User:</strong>
        <%= @sea.user %>
    </p>

    <p>
        <strong>Title:</strong>
        <%= @sea.title %>
    </p>

    <p>
        <strong>Description:</strong>
        <%= @sea.description %>
    </p>

    <p>
        <strong>Tag:</strong>
        <%= @sea.tag %>
    </p>
    <% end %>
    <% end %>
</div>
<%= link_to 'Back', new_searches_path %>